application: ssspiochld
version: 1
runtime: python
api_version: 1

# incluses:
#  - src

builtins:
- datastore_admin: on
- appstats: on
- admin_redirect: on

handlers:
- url: .*
  script: main.py
  
  
  
